language: php

php:
  - '5.4'
  - '5.5.9'
  - '5.6'
  - '7.0'
  - nightly

env:
  - ILLUMINATE_VERSION=5.0.*

matrix:
  include:
    - php: 5.5.9
      env: ILLUMINATE_VERSION=5.1.*
    - php: 5.5.9
      env: ILLUMINATE_VERSION=5.2.*
    - php: 5.6
      env: ILLUMINATE_VERSION=5.1.*
    - php: 5.6
      env: ILLUMINATE_VERSION=5.2.*
    - php: 7.0
      env: ILLUMINATE_VERSION=5.1.*
    - php: 7.0
      env: ILLUMINATE_VERSION=5.2.*
    - php: nightly
      env: ILLUMINATE_VERSION=5.1.*
    - php: nightly
      env: ILLUMINATE_VERSION=5.2.*

before_install:
  - composer require "illuminate/database:${ILLUMINATE_VERSION}" --no-update -v
  - composer require "illuminate/events:${ILLUMINATE_VERSION}" --no-update -v

install: composer update --prefer-source --no-interaction --dev -v

script: vendor/bin/phpunit --debug -c phpunit.xml

notifications:
  slack:
    secure: qp+fY58fT9RBWgWyNfOhTTSj34pnKb4ZGj5Z6Ie2+S0puUun5K66D573IIsXo5vZtdHLLQtAg1O9D5jMtctC1m3V/CJblikr90azskGaX/JrCfT9ME/meZsW8uAR0cfnmuqEK9PIpop6bBKKDeoWLefKKSrC4F4zps9zCarfhXcIyPHjBPZm0foLWN0ngA82JnMKjnmRUBHZja4IGOsX86qQyYfMFm0du7fBsPTavsCFWGPgOE41fxoQIxTqbdWzLqtBj/1Nv+/C3vapDIC7T9R1E6rmxbnRmS65bDd6pRDRtACp8Z4P28AjLR0RDWNhIIF+/b+95lBMkR46bW0ecN3T62PMZKnRGwMdRp+ayy22QKMAoN6qfRZ6oxd5k0j/s/5r50Pq4RH1ivnqd1yiLVPPM0d2q/pYcHHDQUnUmvGg5WBF75PwlccEUX3hgTgB2nlZWXL+iwBINMB8wOyfXJgel3Uu5SCvWmVpHXYOqwskltPtHLnGjt6egrn9JqncjfUMOMPPm8Sz7rErBl0XMos/k81Cbxk94753sUzJ9CwHaxlCXZPl5kr8MGcY68fZexbaBXpFm+nUPQyOVK/3daIBbs7HhnVvMwgLnXVcvGuAeIXMUbzSEka7pV63QjGcot76TidwvtiKDIVaPXKw3UaYFh+ImQzaywrcmkpz4Es=
